# Generated by Django 6.0 on 2025-12-18 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Submitted', max_length=50)),
                ('package_id', models.CharField(max_length=50)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=255)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True)),
                ('services', models.JSONField(default=list)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(default=dict)),
                ('language', models.CharField(max_length=50)),
                ('primary_color', models.CharField(max_length=50)),
                ('theme_style', models.CharField(max_length=50)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('image_urls', models.JSONField(default=list)),
            ],
        ),
    ]
